# permissions for end users to edit flyservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: flyservice-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: fly-service
    app.kubernetes.io/part-of: fly-service
    app.kubernetes.io/managed-by: kustomize
  name: flyservice-editor-role
rules:
- apiGroups:
  - apps.serving.kubefly.tech
  resources:
  - flyservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.serving.kubefly.tech
  resources:
  - flyservices/status
  verbs:
  - get
